# Generated by Django 6.1.2 on 2026-10-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField()),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('porte', models.CharField(choices=[('MP', 'Muito Pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('MG', 'Muito Grande')], max_length=2)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('descricao_animal', models.TextField(default='Sem Descrição.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_publicacao', models.DateField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Desaparecido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=50)),
                ('data_desaparecimento', models.DateField()),
                ('descricao_desaparecido', models.TextField()),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.animal')),
            ],
        ),
    ]
